version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
brews:
  - repository:
      owner: akadir
      name: homebrew-gop
    directory: Formula
    homepage: https://github.com/akadir/gop
    description: simple cli app to open current git repository's remote url in the default browser.
    dependencies:
      - name: git

